### ISSUE TITLE
`load` callback not invoked when doing insert or update

### ISSUE THREAD

**Issue by gjaldon** [elixir-lang/ecto#1241]
refs: https://github.com/gjaldon/ecto_enum/issues/3

In `ecto_enum`, an integer value in the db is converted to a corresponding atom value. 

```elixir
defenum MyApp.Status, pending: 0, in_progress: 1, done: 2

defmodule MyApp.Order do
  field :status, OrderStatus, default: :pending
end

order = Repo.insert! %Order{status: 0}
IO.inspect order.status # => 0

order = Repo.get(Order, 1)
IO.inspect order.status # => :pending
```

Shouldn't we invoke the `load` callback when doing `Repo.insert` or `Repo.update` too? That way, the field will behave consistently on `get`, `insert` and `update`. What do you guys think?

Would be happy to take this on if you think we should go ahead with this minor change.

**Comment by josevalim** [comment]
I believe this is fixed in master.

On Saturday, February 6, 2016, Gabriel Jaldon <notifications@github.com>
wrote:

> refs: gjaldon/ecto_enum#3 <https://github.com/gjaldon/ecto_enum/issues/3>
>
> In ecto_enum, an integer value in the db is converted to a corresponding
> atom value.
>
> defenum MyApp.Status, pending: 0, in_progress: 1, done: 2
> defmodule MyApp.Order do
>   field :status, OrderStatus, default: :pendingend
>
> order = Repo.insert! %Order{status: 0}IO.inspect order.status # => 0
>
> order = Repo.get(Order, 1)IO.inspect order.status # => :pending
>
> Shouldn't we invoke the load callback when doing Repo.insert or
> Repo.update too? That way, the field will behave consistently on get,
> insert and update. What do you guys think?
>
> Would be happy to take this on if you think we should go ahead with this
> minor change.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/ecto/issues/1241>.
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by gjaldon** [comment]
@josevalim I just pulled latest Ecto into `ecto_enum` and tested but I'm still getting the same behavior where `load` callback is not invoked on insert and update.

**Comment by josevalim** [comment]
Ok, I have identifier and this is working as expected. If your field supports both atoms and integers, then both are allowed. The reason we won't load the field it is because it is already in the struct, so we assume the field in the struct is already correct (otherwise this would bring all kinds of implications). Or you need to enforce they are always atoms OR you need to accept they can be mixed :)
