### ISSUE TITLE
Run ecto migration with non-standard path of repo

### ISSUE THREAD

**Issue by asiniy** [elixir-lang/ecto#1428]
### Environment

* Elixir version (elixir -v): 1.2.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): pg 9.5
* Ecto version (mix deps): 1.1.7
* Operating system: ubuntu 15.04

I'm not sure it's a bug or my missunderstanding of ecto (but it looks like a bug), so I placed issue here and a [question at SO](http://stackoverflow.com/questions/37224574/run-ecto-migration-with-non-standard-path-of-repo). You can close this issue if you think it isn't a bug.

I have a "dummy" app in my mix app, so, it's first migration is placed in `test/dummy/priv/repo/migrations/20160323060044_create_user.exs`.

I want to run this migration, but it returns `11:19:20.647 [info]  Already up`, and this disappoints me.

Here is my `test.exs`:

    config :ecto_state_machine, Dummy.Repo,
      adapter: Ecto.Adapters.Postgres,
      username: System.get_env("USER"),
      password: "posgtres",
      database: "ecto_state_machine_test",
      pool_size: 10,
      port: 5432,
      priv: "test/dummy/priv/repo/"
Here is my migration:

    defmodule Dummy.Repo.Migrations.CreateUser do
      use Ecto.Migration
    
      def change do
        create table(:users) do
          add :state, :string, null: false
          add :confirmed_at, :datetime
    
          timestamps
        end
      end
    end

I'm running

    MIX_ENV=test mix ecto.migrate -r Dummy.Repo

and get annoying `already up` instead of migration. What's I'm doing wrong?

My attempts:

1. I tried to drop and re-create database, nothing happened

2. My another turn was to require the code. I tried to implement this in my `test.exs` or `dev.exs`, but I received `module Ecto.Migration is not loaded and could not be found

    `"test/dummy/priv/repo/migrations"
    |> Path.join("**/*.exs")
    |> Path.wildcard
    |> Enum.map(&Code.require_file/1)`

3. I also tried to create a fake migration by `MIX_ENV=test mix ecto.gen.migration f -r Dummy.Repo`, fill it with code which raise an exception, and than I had 

    `MIX_ENV=test mix ecto.migrate -r Dummy.Repo # => 12:49:00.932 [info]  Already up`

4. I also tried to load shell `MIX_ENV=test`, then invoke code from 2nd approach, then `Mix.Task.run "ecto.migrate" ["-r", "Dummy.Repo"]`. it returned :noop to me?

Is it a bug or I missed something? Alex

**Comment by josevalim** [comment]
This is fixed in Ecto 2.0.0-rc. In previous versions, migrations would always have to be inside priv. We have removed this requirement in Ecto 2.0.

**Comment by asiniy** [comment]
@josevalim I updated ecto up to `2.0.0-rc5`. Problem is still here

**Comment by josevalim** [comment]
Can you provide a sample app that reproduces the error then so we can take a look? Thank you!

**Comment by asiniy** [comment]
@josevalim Jose, here it is: https://github.com/asiniy/ecto_state_machine/pull/1

btw, how can I offer article for elixir-radar?

**Comment by josevalim** [comment]
You are right. This feature won't work. "priv" should always point to a subdirectory inside priv. I will update the docs to make it clear. Thank you for trying it out and uncovering the limitation. :)

About elixir-radar, you can send an e-mail to elixir dot radar at plataformatec dot com dot br.

Finally, I would recommend you to revisit the state machine for Ecto. Ecto 2.0 is moving away from the idea of models and callbacks to focus on data. You are even invoking repos from inside the schema, which is a big no-no even in Ecto 1.0 times. :)

**Comment by asiniy** [comment]
Thanks, it works!

@josevalim I can't actually understand intention of this limitation. Why can't I place under another directory, than `priv`?

How can I implement state machine via Ecto 2 in your opinion?

**Comment by josevalim** [comment]
@asiniy we need to rely on the information being inside the _build directory so it works on umbrella directories and so on. And only `priv` and `ebin` are copied to _build.

I think a state machine should be implemented for Elixir data, it is not related to Ecto 2.0 at all.

**Comment by asiniy** [comment]
@josevalim interesting idea, I'll move state machine from ecto namespace just to maps.

**Comment by bill-mybiz** [comment]
Howdy. Love Elixir. Lots of love in the documentation, which is the best part IMO. In that vein, I wanted to point out that the docs for [`Ecto.Migrate`](https://hexdocs.pm/ecto/Mix.Tasks.Ecto.Migrate.html) and [`Ecto.Gen.Migration`](https://hexdocs.pm/ecto/Mix.Tasks.Ecto.Gen.Migration.html) still don't mention the requirement that the folder **must** be a subdirectory in the `priv` folder. I've forked and committed a [possible tweak to the documentation](https://github.com/bill-mybiz/ecto/commit/2a5e8cdcf6d4f73015f9a2bec5a8482358af3133). Should I go ahead and create a pull request?

Also, if the directory is invalid, I would think the `mix ecto.gen.migration` should fail.

**Comment by josevalim** [comment]
Yes, please send a pull request! Docs improvements are always welcome!
